### PR TITLE
Migrate Maven to Gradle 

### PR DESCRIPTION
**Pull request by aravind666**
Maven's POM keeps growing along with the project,  the moment POM files grow big it becomes harder to maintain because XML by itself is not meant for humans AFAIK it is meant for someone else who has interfaces to defined to  interpret it  :)  .  I saw lots of advantages in using Gradle some very few and cool ones are 

1. Gradle is one such beautiful thing which provides nice DSL to write build tasks by helping me with conventions as well as giving me power to overide it. 
2. The plugin ecosystem of Gradle is simply amazing, and also it is too easy to build one for ourself if required or consume some thing from mavencentral as well in our gradle builds 
3. Gradle has some general support , for building C++ 
4. Unlike maven which requires some sort of full compilation, Now I can ask people to just clone and run using gradle and in that mode I can do some language agnostic stuff. For eg.. now post doing this change you can run
   `./gradlew run`  from the root directory which simply runs the application just like running JAR.  
5. It allows me to watch my tests continuously [https://docs.gradle.org/current/userguide/command_line_interface.html#sec:continuous_build](url)
6. Last but not least, Since Gradle allows me to write build tasks using a full fledged Groovy language, Just Incase I hit a roadblock in future worst case I can resolve it by adding some another level of indirection, which is somewhat not so easy in Maven.

### CODE REVIEW

**Comment by dsvellal** [comment]
Do we at least have a manual (or automated) test completed that demonstrates at each gate point you have seen correct code accepted and faulty code rejected? "Fails when it should, passes when it should".

**Comment by kryptt** [comment]
Did you consider sbt over gradle? there is great support with the native-packager to build binaries with graalvm, etc. 
And it might simplify adding scala sources to this project :D

**Comment by aravind666** [comment]
@kryptt ,  You are correct, infact that is one of the reasons why I migrated to Gradle, you can still add scala code to this repo and generate a fat jar, consume all dependencies to create a hound in scala as well as in C++, previously that was not so easy . 

Thanks for bringing SBT in conversation,  it is just that the scala DSL syntax is a kind of nightmare :) for me not because it is bad it is because of me not so used to that syntax .

**Comment by aravind666** [comment]
@dsvellal , my Unit tests are calling at commandline context and they are running with out any exceptions. I am running the same rules and same gates only interface is changed, previously those rules were run using Maven and now they are running using Gradle.  I had some failed builds and I identified them at local , also you can see my commit below 

https://github.com/philips-software/cerberus/pull/21/commits/f80762153f07d33c744d713c453308e1c85ea3cf

**Review by kryptt — APPROVED** [review]
Generally looks good,

**Review by dsvellal — APPROVED** [review]

**Comment by dsvellal** [comment]
LGTM!

**Pull request merged**
